application:
  name: "\${spring.application.name}"

spring:
  application:
    name: Movies-Worker
  rabbitmq:
    host: "\${RABBITMQ_HOST:localhost}"
    port: "\${RABBITMQ_PORT:5672}"
    virtual-host: "\${RABBITMQ_VIRTUAL_HOST:/}"
    username: "\${RABBITMQ_USERNAME:guest}"
    password: "\${RABBITMQ_PASSWORD:guest}"

rabbitmq:
  queues:
    movies:
      create-movie:
        name: "\${RABBITMQ_QUEUE_SAVE_MOVIE:create-movie-queue}"